package com.strik3forc3.ytdownloader.core

/**
 * Serialises cookies into the Netscape `cookies.txt` format that yt-dlp's `--cookies`
 * flag reads.
 *
 * Android's `CookieManager.getCookie(url)` returns only a `name=value; name=value`
 * string — no domain, path or expiry — so the surrounding fields are reconstructed from
 * the URL the cookies were read for.
 */
object NetscapeCookies {

    private const val HEADER = "# Netscape HTTP Cookie File\n" +
        "# Generated by YT Downloader. Do not edit.\n"

    /** Ten years out. yt-dlp discards anything already expired. */
    private const val EXPIRY_SECONDS = 10L * 365 * 24 * 60 * 60

    data class Cookie(val domain: String, val name: String, val value: String)

    /**
     * Splits a `CookieManager` header into individual cookies.
     *
     * @param domain the cookie domain, e.g. `.youtube.com`.
     */
    fun parseHeader(domain: String, header: String?): List<Cookie> =
        header.orEmpty()
            .split(';')
            .mapNotNull { part ->
                val trimmed = part.trim()
                val separator = trimmed.indexOf('=')
                if (separator <= 0) return@mapNotNull null
                Cookie(
                    domain = domain,
                    name = trimmed.substring(0, separator).trim(),
                    value = trimmed.substring(separator + 1).trim(),
                )
            }
            .filter { it.name.isNotEmpty() }

    /** Renders a complete cookie file. Later duplicates of a name within a domain win. */
    fun render(cookies: List<Cookie>, nowSeconds: Long): String {
        val deduplicated = LinkedHashMap<Pair<String, String>, Cookie>()
        for (cookie in cookies) {
            deduplicated[cookie.domain to cookie.name] = cookie
        }

        val expiry = nowSeconds + EXPIRY_SECONDS
        return buildString {
            append(HEADER)
            for (cookie in deduplicated.values) {
                // domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
                append(cookie.domain).append('\t')
                append(if (cookie.domain.startsWith(".")) "TRUE" else "FALSE").append('\t')
                append('/').append('\t')
                append("TRUE").append('\t')
                append(expiry).append('\t')
                append(cookie.name).append('\t')
                append(cookie.value).append('\n')
            }
        }
    }

    /**
     * Whether a cookie set looks like a signed-in YouTube session. Used to tell the user
     * the login actually took, rather than writing an empty file and failing later with
     * an opaque bot-check error.
     */
    fun looksAuthenticated(cookies: List<Cookie>): Boolean =
        cookies.any { it.name.equals("SAPISID", ignoreCase = true) } ||
            cookies.any { it.name.equals("__Secure-3PAPISID", ignoreCase = true) }
}
